version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "${PUBLIC_WEBSERVER_PORT}:80"
    depends_on:
      - cookiecutter
    links:
      - "cookiecutter"

  cookiecutter:
    build:
      context: .
      dockerfile: Dockerfile-cookiecutter
    ports:
      - 5006
      - 5432

  database:
    build:
      context: .
      dockerfile: Dockerfile-postgresql
    environment:
      POSTGRES_USER: cookiecutter
      POSTGRES_PASSWORD: cookiecutter
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
  
volumes:
  pg-data:
